version: "3.8"

services:
    #RabbitMQ
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672

    #Notification service
    notification-service:
        image: notification-service
        container_name: notification-service
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8082:8082
        depends_on:
            - rabbitmq
        environment:
            - SPRING_RABBITMQ_HOST=rabbitmq
