version: "3.8"

services:
   rabbitmq:
     image: rabbitmq:3-management
     ports:
     - 5672:5672
     - 15672:15672

   api-gateway:
       build: ./NotificationService
       restart: always
       container_name: api-gateway
       depends_on:
           - rabbitmq
       ports:
           - 8083:8083